#!/usr/bin/env bash
# Displays information about subdomains

function get_record_info() {
  local domain="$1"
  local subdomain="$2"
  local record_type="$(dig +short "$subdomain.$domain" | awk '{print $1}')"
  local destination="$(dig +short "$subdomain.$domain")"
  echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
  subdomains=("www" "lb-01" "web-01" "web-02")
else
  subdomains=("$subdomain")
fi

for subdomain in "${subdomains[@]}"; do
  get_record_info "$domain" "$subdomain"
done
