#!/usr/bin/env bash
# Transfers a file from our clients to a server

file_path_to_be_transferred=$1
ip=$2
username=$3
path_to_private_key=$4

i=0;
for _ in "$@"
do
	i=$((i + 1));
done

if [ $i == 4 ]
then
	scp -o StrictHostKEyChecking=no -i "$path_to_private_key" "$file_path_to_be_transferred" "$username"@"$ip":~/
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
fi
