#!/bin/bash
# This script transfers a file from a client to a server using SCP.
# The script accepts 4 parameters:
# - The path to the file to be transferred
# - The IP of the server we want to transfer the file to
# - The username SCP connects with
# - The path to the SSH private key that SCP uses

if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

scp -o StrictHostKeyChecking=no -i $path_to_ssh_key $path_to_file $username@$ip:~/
