#!/usr/bin/env bash
# Update package list and install Nginx webserver

# Install nginx
sudo apt-get update
sudo apt-get install nginx -y

# Configure nginx
sudo echo "server {
    listen 80;
    location / {
        echo 'Hello World!';
    }
}" > /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart
