#!/usr/bin/env bash
# Install nginx on your web-01
# Check if Nginx is installed
if ! command -v nginx &> /dev/null; then
    # Update package lists and install Nginx
    sudo apt-get update
    sudo apt-get install -y nginx
fi

# Configure Nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Check if the custom index.html file exists
if [ ! -f /var/www/html/index.html ]; then
    # Create a custom index.html file with the "Hello World!" content
    echo "Hello World!" | sudo tee /var/www/html/index.html
fi

# Set up /redirect_me to a YouTube video if it doesn't exist
if ! sudo grep -q "location \/redirect_me" /etc/nginx/sites-available/default; then
    sudo sed -i '/^server {/a \    location \/redirect_me {\n        return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;
fi

# Restart Nginx without using systemctl
sudo service nginx restart
