#!/usr/bin/env bash

# Install Nginx if not already installed
if ! [ -x "$(command -v nginx)" ]; then
  sudo apt update
  sudo apt install -y nginx
fi

# Create the redirect configuration file
sudo tee /etc/nginx/sites-available/redirect_me << EOF
server {
    listen 80;
    listen [::]:80;

    server_name _;

    location /redirect_me {
        return 301 https://www.example.com/;
    }
}
EOF

# Enable the redirect configuration
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Remove the default Nginx configuration
sudo rm /etc/nginx/sites-enabled/default

# Test the configuration and restart Nginx
sudo nginx -t
sudo service nginx restart
