#!/usr/bin/env bash
# Install nginx on your web-01
# Check if Nginx is installed
if ! command -v nginx &> /dev/null; then
    # Update package lists and install Nginx
    sudo apt-get update
    sudo apt-get install -y nginx
fi

# Configure Nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Check if the custom index.html file exists
if [ ! -f /var/www/html/index.html ]; then
    # Create a custom index.html file with the "Hello World!" content
    echo "Hello World!" | sudo tee /var/www/html/index.html
fi

# Setting up /redirect_me to a youtube video
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Restart Nginx without using systemctl
sudo service nginx restart
