#!/usr/bin/env bash
# Configure the Nginx server to have a custom 404 page
# that contains the string Ceci n'est pas une page.

sudo apt-get update -y
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

sudo sed -i "/^server {/a \\
		location /redirect_me { \\
				return 301 \"https://www.alxafrica.com/\"; \\
		} \\
	error_page 404 /custom_404.html; \\
	location = /custom_404.html { \\
			root /var/www/html; \\
			internal; \\
		}" /etc/nginx/sites-available/default

sudo service nginx restart
