#!/usr/bin/env bash
# Install nginx on your web-01
# Check if Nginx is installed
if ! command -v nginx &> /dev/null; then
    # Update package lists and install Nginx
    sudo apt-get update
    sudo apt-get install -y nginx
fi

# Configure Nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Check if the custom index.html file exists
if [ ! -f /var/www/html/index.html ]; then
    # Create a custom index.html file with the "Hello World!" content
    echo "Hello World!" | sudo tee /var/www/html/index.html
fi

# Set up /redirect_me to a YouTube video if it doesn't exist
if ! sudo grep -q "location \/redirect_me" /etc/nginx/sites-available/default; then
    sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
fi

# Configure custom 404 page
if ! sudo grep -q "error_page 404" /etc/nginx/sites-available/default; then
    # Create the custom 404 page
    echo "Ceci n'est pas une page." | sudo tee /var/www/html/custom_404.html

    # Configure Nginx to use the custom 404 page
    sudo sed -i '25i\	error_page 404 /custom_404.html;' /etc/nginx/sites-available/default
    sudo sed -i '26i\	location = /custom_404.html {' /etc/nginx/sites-available/default
    sudo sed -i '27i\		internal;' /etc/nginx/sites-available/default
    sudo sed -i '28i\	}' /etc/nginx/sites-available/default
fi

# Restart Nginx without using systemctl
sudo nginx -t && sudo service nginx restart
