#!/usr/bin/env bash
# Install nginx on your web server if it is not already installed
if [ ! -x "$(command -v nginx)" ]; then
  sudo apt update
  sudo apt install -y nginx
fi

# Create a custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Configure Nginx to use the custom 404 error page
sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    root /var/www/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        internal;
        add_header Content-Type text/html;
        add_header ETag "58acb50e-1a";
    }
}
EOF'

# Restart Nginx
sudo service nginx restart
