#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header.

sudo apt-get update -y
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

sudo sed -i "/^server {/a \\
		location /redirect_me { \\
				return 301 \"https://www.youtube.com/watch?v=QH2-TGUlwu4\"; \\
		} \\
	error_page 404 /custom_404.html; \\
	location = /custom_404.html { \\
			root /var/www/html; \\
			internal; \\
		}" /etc/nginx/sites-available/default

host_name="$HOSTNAME"

sudo sed -i "/Default server configuration/a add_header X-Served-By '${host_name}';" /etc/nginx/sites-available/default
sudo service nginx restart
