#!/usr/bin/env bash
# Update Ubuntu package manager
sudo apt-get update

# Install Nginx
sudo apt-get install nginx

# Create a custom Nginx configuration file
sudo echo "add_header X-Served-By $hostname;" > /etc/nginx/conf.d/custom-header.conf

# Test Nginx configuration file for syntax errors
sudo nginx -t

# Reload Nginx to apply the new configuration
sudo systemctl reload nginx
