#!/usr/bin/env bash
# Install HAproxy
sudo apt-get -y update
sudo apt-get install -y haproxy

# Configure HAproxy
echo "frontend web-frontend
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    mode http
    balance roundrobin
    server 105044-web-01:80 check
    server 105044-web-02:80 check" > /etc/haproxy/haproxy.cfg

# Enable HAproxy init script
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Start HAproxy
sudo service haproxy start
