#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# display hours from 0 to 12
# display minutes from 1 to 59

hours=0
while [ $hours -le 12 ]
do
    echo "Hour: $hours"
    minute=1
    while [ $minute -le 59 ]
    do
        echo "$minute"
        (( minute++ ))
    done
    (( hours++ ))
done
