#!/usr/bin/env bash
#install the ufw firewall and setup a few rules on web-01
# Check if UFW is installed
if ! command -v ufw &> /dev/null; then
    # UFW is not installed, so install it
    sudo apt update
    sudo apt install ufw -y
fi

# Set default rules to deny incoming and allow outgoing traffic
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow incoming SSH (port 22), HTTPS (port 443), and HTTP (port 80) traffic
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Enable UFW
sudo ufw enable

# Show UFW status and rules
sudo ufw status
