#!/usr/bin/env bash
# configure it to our needs so that you can connect to
# a server without typing a password.

Host myserver
    Hostname 172.17.0.1
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
